---
title: "README"
format: gfm
---

<!-- README.md is generated from README.qmd - edit that file -->

# Pollution & Prejudice

NOTE: this is an update to the Redline Mapping project contained here: <https://github.com/daltare/Redline-Mapping>

## Background

The purpose of this project is to analyze present-day environmental and socioeconomic conditions in neighborhoods in California cities that were assessed by the federal Home Owners' Loan Corporation (HOLC) in the 1930s. As part of its assessment process, the HOLC produced maps that are today commonly known as "Redlining" maps, which divided up selected cities (generally those with a population greater than 40,000) into neighborhoods, and assigned each of those neighborhoods a grade that reflected its percieved credit worthiness, on a scale of A (Best) through D (Hazardous). Those assessments often included explicit references to both the racial makeup of a neighborhood's population and the environmental conditions in and around that neighborhood as important factors in assigning each neighborhood's grade.

Our goal is to analyze whether or not present-day pollution burdens, as well as vulnerability to the effects of pollution (due to socioeconomic conditions), tend to show any association with historical HOLC grade in neighborhoods assessed by the HOLC in the 1930s. In other words, we are exploring whether historical HOLC grade continues to be a possible predictor of present-day environmental and socioeconomic conditions. We also explore the present-day racial / ethnic makeup of those neighborhoods, to assess whether racial disparities by HOLC grade tend to persist today.

## Data Sources

The primary data sources used in this analysis are:

-   [Mapping Inequality: Redlining in New Deal America](https://dsl.richmond.edu/panorama/redlining/#loc=6/36.37/-121.816)
    -   provides the HOLC (or "Redlining") maps, which are available to download in various formats
    -   a version of the dataset processed for use in this analysis (including data for all 8 California urban areas assessed by the HOLC) is available to download at [this link](https://github.com/daltare/pollution-and-prejudice/raw/main/tar_data_processed/holc_data/redline_maps_processed.gpkg)
-   [CalEnviroScreen 4.0](https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40)
    -   assesses relative pollution burden and vulnerability for each census tract in California, providing an overall score as well as scores for 21 specific indicators of pollution burden or population characteristics for each tract, available to access/download in various formats
    -   a version of the dataset processed for use in this analysis (with cleaned / expanded field names, missing values encoded as `NA`, and revised geographic representation of census tracts - to fix inconsistent boundaries between tracts - based on simplified 2010 TIGER data) is available to download at [this link](https://github.com/daltare/pollution-and-prejudice/raw/main/tar_data_processed/ces_data/calenviroscreen_4-0_processed_tiger_simple.gpkg)

## Analytical Process and Results

For an overview of the analytical process and results, see the [summary_report.md](tar_reports/summary_report.md) document.

The primary results are available in the `tar_data_results/redline_CES_scores.gpkg` file, which can be downloaded using [this link](https://github.com/daltare/pollution-and-prejudice/raw/main/tar_data_results/HOLC_CES_scores_demographics.gpkg). This file includes estimated CalEnviroScreen 4.0 scores and estimated population by racial / ethnic group for each neighborhood in the 1930s HOLC maps. Note that the CES scores and demographics in this dataset are estimates that are intended to be used for relative comparisons across groups, and should be used with caution when looking at individual or small numbers of neighborhoods in isolation.

## Reproducibility

### Workflow - {targets}

This project uses the [`targets` package](https://docs.ropensci.org/targets/) for workflow management. The entire workflow is defined and managed through the [\_targets.R](_targets.R) file.

Run `targets::tar_make()` from the console to run the workflow and reproduce all results. For some more pointers on using the `targets` package, see the [targets_notes.md](targets_notes.md) file.

#### Targets workflow:

This figure provides a visualization of the workflow defined in the [\_targets.R](_targets.R) file:

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

cat(
    "```mermaid",
    suppressMessages(targets::tar_mermaid(targets_only = FALSE)),
    "```",
    sep = "\n"
)
#this should display correctly on GitHub, or code can be pasted into https://mermaid.live
```

### Package Management - {renv}

This project uses [`renv`](https://rstudio.github.io/renv/articles/renv.html) for package management. When opening this project as an RStudio Project for the first time, `renv` should automatically install itself and prompt you to run `renv::restore()` to install all package dependencies.
